### ISSUE TITLE
SDL_CreateGPUDevice 'name' param should allow null pointer as input

### ISSUE THREAD

**Issue by NoelFB** [flibitijibibo/SDL3-CS#14]
The method `SDL_CreateGPUDevice` allows the name parameter to be a null pointer to let SDL pick the underlying GPU driver, but the generated bindings take a string which doesn't allow for that. Could maybe be an `IntPtr`, even though that's less user-friendly? Or alternatively a nullable string in Core, but I'm not sure how that would play with the interop.

EDIT: I've actually got a few others:
 - `SDL_SetWindowFullscreenMode`: 'mode' should allow null ptr as a valid input, but is currently `ref` in Core
 - `SDL_BeginGPURenderPass`: 'depth_stencil_target_info' should allow null ptr as a valid input, but is currently `in` in Core

**Comment by thatcosmonaut** [comment]
I'm pretty sure you can pass null for the string input. For the latter two you can use Unsafe.NullRef.

**Comment by NoelFB** [comment]
I think I've gotten so used to nullable I didn't even think to pass in a null string. That makes sense, haha. Sorry for the non-issue, these all seem good then!
