### ISSUE TITLE
'Unable to load DLL 'SDL3' exception when trying to run CreateWindow()

### ISSUE THREAD

**Issue by DrMayx** [flibitijibibo/SDL3-CS#28]
EXCEPTION:
![image](https://github.com/user-attachments/assets/7b1cc8d7-7fb1-4698-bf62-4fc1516fdb42)

MY CODE:
![image](https://github.com/user-attachments/assets/d8fe5f48-1f8f-489a-bc83-4e205c6c20f5)

PROJECT
![image](https://github.com/user-attachments/assets/72f56418-0757-4f2c-ace3-cc6f9af377b9)

Hi,

I'm new to all this but I think I generated the bindings correctly and copied the DLL and PDB to the C# project and linked it as my code finds the SDL methods but it looks like it can't find the base SDL3 lib. Do you have any idea how might I solve this ?

I couldn't find any tutorial on how to set the bindings and SDL for c# online so maybe I just did something wrong.

Thanks in advance for any help here

**Comment by thatcosmonaut** [comment]
The SDL dll has to be next to the built C# executable when it runs so the runtime can load it. This is standard native interop. You can either copy the dll to the build directory by hand or set up a csproj directive to copy it to the build directory automatically at build time.

**Comment by DrMayx** [comment]
Thank you :) I was copying it to \Lib directory and not right next to SDL3.Core lib
