### ISSUE TITLE
SDL_GetEventFilter first parameter is not fully detected as a pointer

### ISSUE THREAD

**Issue by flibitijibibo** [flibitijibibo/SDL3-CS#3]
It knows enough to throw IntPtr there, but doesn't give UserProvidedData the option to alias it to `out SDL_EventFilter`.

**Comment by cryy22** [comment]
resolved; the program now produces an SDL_GetEventFilter identical to the manual edit. the fix also resolved the same issue in `SDL_GetLogOutputFunction`.
