### ISSUE TITLE
SDL_Event padding is generated incorrectly

### ISSUE THREAD

**Issue by flibitijibibo** [flibitijibibo/SDL3-CS#4]
Instead of generating a `fixed byte[128]` it generates 128 padding byte fields all at offset 0 - this was a fun native crash to diagnose!

**Comment by cryy22** [comment]
lmao sorryyy. resolved now; i just consolidated on using fixed-length buffers for all inline array fields wherever possible. my ide says fixed-length buffers aren't supported for non-primitive types so i still had to do the numbered fields thing for `SDL_MessageBoxColorScheme`.
